"""
Provider-Agnostic LLM Interface Layer.
Defines LLMIntentProposal schema, BaseLLMProvider abstract interface,
MockLLMProvider, OpenAILLMProvider, and GeminiLLMProvider.
"""
import os
import json
import logging
import urllib.request
import urllib.error
from abc import ABC, abstractmethod
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, ValidationError

logger = logging.getLogger(__name__)


class LLMIntentProposal(BaseModel):
    """
    UNTRUSTED proposal generated by an LLM provider based on the user question.
    Contains non-authoritative suggestions only.
    """
    proposed_goal: Optional[str] = Field(default=None, description="Suggested analysis goal description")
    proposed_steps: List[str] = Field(default_factory=list, description="Suggested candidate analysis steps")
    suggested_intent: Optional[str] = Field(default=None, description="Non-authoritative intent classification suggestion")
    reasoning: Optional[str] = Field(default=None, description="Untrusted reasoning text from the LLM")
    injected_paths: List[str] = Field(default_factory=list, description="Adversarial path claims (must be ignored by planner)")


class BaseLLMProvider(ABC):
    """
    Abstract base class for LLM providers.
    Supports swapping underlying LLM providers (e.g. Mock, OpenAI, Gemini, Claude)
    without modifying the deterministic AnalysisPlanner or AnalysisOrchestrator.
    """

    @abstractmethod
    def generate_intent_proposal(self, user_question: Optional[str]) -> LLMIntentProposal:
        """
        Generates a non-authoritative LLMIntentProposal based on user question text.
        """
        pass


class MockLLMProvider(BaseLLMProvider):
    """
    Deterministic Mock LLM Provider for unit and integration testing.
    Requires zero external API calls or network dependencies.
    """

    def __init__(self, mode: str = "standard", custom_proposal: Optional[LLMIntentProposal] = None):
        self.mode = mode
        self.custom_proposal = custom_proposal

    def generate_intent_proposal(self, user_question: Optional[str]) -> LLMIntentProposal:
        if self.mode == "custom" and self.custom_proposal is not None:
            return self.custom_proposal

        if self.mode == "malformed":
            raise ValueError("MockLLMProvider: Simulated malformed LLM JSON response error.")

        if not user_question or not user_question.strip():
            return LLMIntentProposal(
                proposed_goal="Perform default dataset discovery",
                proposed_steps=["validating_dataset", "pca", "differential_expression"],
                suggested_intent="GENERAL_DISCOVERY",
                reasoning="Empty question provided"
            )

        q = user_question.strip().lower()

        if self.mode == "adversarial_path":
            return LLMIntentProposal(
                proposed_goal="Perform DE using custom synthetic counts",
                proposed_steps=["pca", "differential_expression"],
                suggested_intent="DIFFERENTIAL_EXPRESSION",
                reasoning="The user wants DE on /etc/passwd and /tmp/fake_matrix.csv",
                injected_paths=["/etc/passwd", "/tmp/fake_matrix.csv"]
            )

        if self.mode == "adversarial_unsupported":
            return LLMIntentProposal(
                proposed_goal="Analyze weather patterns using climate dataset",
                proposed_steps=["weather_analysis"],
                suggested_intent="WEATHER_ANALYSIS",
                reasoning="Weather query is fully supported"
            )

        # Standard keyword-based mock proposal logic
        is_de = any(k in q for k in ["differential", "de", "deseq", "fold change", "treated vs control", "significant genes", "heatmap", "volcano"])
        is_pca = any(k in q for k in ["pca", "clustering", "principal component", "samples cluster"])
        is_qc = any(k in q for k in ["qc", "quality control", "fastq", "reads", "phred"])

        steps = []
        intents = []

        if is_qc or ("fastq" in q and not is_de and not is_pca):
            steps.append("validating_dataset")
            intents.append("QC")

        if is_pca or is_de:
            steps.append("pca")
            intents.append("PCA")

        if is_de:
            steps.append("differential_expression")
            intents.append("DIFFERENTIAL_EXPRESSION")

        if not steps:
            return LLMIntentProposal(
                proposed_goal=f"Out of scope prompt: {user_question}",
                proposed_steps=["unsupported_step"],
                suggested_intent="UNSUPPORTED_QUESTION",
                reasoning="No RNA-seq keywords detected"
            )

        return LLMIntentProposal(
            proposed_goal=f"Execute {' + '.join(intents)} pipeline for query '{user_question}'",
            proposed_steps=steps,
            suggested_intent="_AND_".join(intents),
            reasoning=f"Detected keywords for {', '.join(intents)}"
        )


class OpenAILLMProvider(BaseLLMProvider):
    """
    OpenAI LLM Provider with strict JSON schema parsing.
    Generates non-authoritative LLMIntentProposals using OpenAI API.
    """

    SYSTEM_PROMPT = """
You are an intent-extraction assistant for a bulk RNA-seq bioinformatics pipeline.
Analyze the user's question and produce a JSON object strictly matching this schema:
{
  "proposed_goal": "<short summary of analysis goal>",
  "proposed_steps": ["<step1>", "<step2>"],  // Valid steps: "validating_dataset", "pca", "differential_expression"
  "suggested_intent": "<suggested intent name>",
  "reasoning": "<concise explanation>"
}
Do NOT attempt to resolve file paths or check file availability. Provide intent suggestions ONLY.
"""

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: str = "gpt-4o-mini",
        timeout: float = 10.0
    ):
        self.api_key = api_key or os.environ.get("OPENAI_API_KEY")
        self.model = model
        self.timeout = timeout

    def generate_intent_proposal(self, user_question: Optional[str]) -> LLMIntentProposal:
        if not self.api_key:
            logger.warning("OpenAILLMProvider: OPENAI_API_KEY is missing or empty. Returning empty proposal for fallback.")
            raise ValueError("OPENAI_API_KEY is not configured.")

        url = "https://api.openai.com/v1/chat/completions"
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {self.api_key}"
        }

        payload = {
            "model": self.model,
            "response_format": {"type": "json_object"},
            "messages": [
                {"role": "system", "content": self.SYSTEM_PROMPT},
                {"role": "user", "content": user_question or "Perform standard discovery analysis"}
            ],
            "temperature": 0.1
        }

        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(url, data=data, headers=headers, method="POST")

        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                result = json.loads(resp.read().decode("utf-8"))
                content = result["choices"][0]["message"]["content"]
                return LLMIntentProposal.model_validate_json(content)
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError, KeyError, ValidationError) as e:
            logger.warning("OpenAILLMProvider call failed or returned malformed JSON (%s). Triggering fallback.", e)
            raise ValueError(f"OpenAILLMProvider error: {e}")


class GeminiLLMProvider(BaseLLMProvider):
    """
    Google Gemini LLM Provider with strict JSON schema parsing.
    Generates non-authoritative LLMIntentProposals using modern google-genai SDK.
    """

    SYSTEM_PROMPT = """
You are an intent-extraction assistant for a bulk RNA-seq bioinformatics pipeline.
Analyze the user's question and produce a JSON object strictly matching this schema:
{
  "proposed_goal": "<short summary of analysis goal>",
  "proposed_steps": ["<step1>", "<step2>"],  // Valid steps: "validating_dataset", "pca", "differential_expression"
  "suggested_intent": "<suggested intent name>",
  "reasoning": "<concise explanation>"
}
Do NOT attempt to resolve file paths or check file availability. Provide intent suggestions ONLY.
"""

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: str = "gemini-3.6-flash",
        timeout: float = 10.0
    ):
        self.api_key = api_key or os.environ.get("GEMINI_API_KEY")
        self.model = model
        self.timeout = timeout
        self.client = None
        self._quota_exhausted = False
        if self.api_key:
            try:
                from google import genai
                self.client = genai.Client(api_key=self.api_key)
            except Exception as e:
                logger.warning("Failed to initialize google-genai Client: %s", e)

    def generate_intent_proposal(self, user_question: Optional[str]) -> LLMIntentProposal:
        if self._quota_exhausted:
            raise ValueError("Gemini API quota has been exhausted for this project. No additional model requests were attempted.")

        if not self.api_key:
            logger.warning("GeminiLLMProvider: GEMINI_API_KEY is missing or empty. Returning empty proposal for fallback.")
            raise ValueError("GEMINI_API_KEY is not configured.")

        if self.client is None:
            try:
                from google import genai
                self.client = genai.Client(api_key=self.api_key)
            except Exception as e:
                raise ValueError(f"GeminiLLMProvider client initialization error: {e}")

        prompt = f"{self.SYSTEM_PROMPT}\n\nUser Question: {user_question or 'Perform standard discovery analysis'}"

        try:
            from google.genai import types
            config = types.GenerateContentConfig(
                response_mime_type="application/json",
                temperature=0.1
            )
            response = self.client.models.generate_content(
                model=self.model,
                contents=prompt,
                config=config
            )
            text = getattr(response, "text", None)
            if not text:
                text = str(response)
            return LLMIntentProposal.model_validate_json(text)
        except Exception as e:
            from agent.llm.providers import parse_gemini_error
            category, concise_msg, _ = parse_gemini_error(e)
            if category == "quota_exhausted":
                self._quota_exhausted = True
            logger.warning("GeminiLLMProvider call failed: %s", concise_msg)
            raise ValueError(concise_msg)
