"""
Generic BaseTool and ToolResult Execution Contract for AI Agent Platform.

Provides a strongly-typed, provider-agnostic abstraction for exposing
deterministic computational capabilities (Python, R, DESeq2, KEGG, RAG, etc.) to AI orchestrators.
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Any, Optional, Tuple, Type
from pydantic import BaseModel, Field, ValidationError


class ToolArtifact(BaseModel):
    """Reference metadata for a file or artifact generated by a tool."""
    artifact_type: str = Field(..., description="File extension or type (e.g. csv, tsv, png, svg, pdf, json)")
    path: str = Field(..., description="Absolute or relative file path to the generated artifact")
    description: Optional[str] = Field(None, description="Human-readable description of the artifact")
    sha256: Optional[str] = Field(None, description="SHA-256 integrity checksum if computed")


class ToolError(BaseModel):
    """Machine-readable error information when a tool execution fails."""
    error_type: str = Field(..., description="Exception or error type name")
    message: str = Field(..., description="User-friendly error message")
    details: Optional[List[str]] = Field(default_factory=list, description="Additional context or validation errors")


class ToolResult(BaseModel):
    """Structured execution result returned by all BaseTool instances."""
    tool_name: str = Field(..., description="Name of the tool that executed")
    status: str = Field(..., description="Execution status: 'success' or 'error'")
    result: Dict[str, Any] = Field(default_factory=dict, description="Structured key-value computation outputs")
    artifacts: List[ToolArtifact] = Field(default_factory=list, description="References to output files created by tool")
    provenance: Dict[str, Any] = Field(default_factory=dict, description="Metadata tracking dataset IDs, parameters, and timestamps")
    error: Optional[ToolError] = Field(None, description="Error details if status is 'error'")

    @classmethod
    def success_result(
        cls,
        tool_name: str,
        result: Dict[str, Any],
        artifacts: Optional[List[ToolArtifact]] = None,
        provenance: Optional[Dict[str, Any]] = None
    ) -> "ToolResult":
        """Construct a successful ToolResult."""
        return cls(
            tool_name=tool_name,
            status="success",
            result=result,
            artifacts=artifacts or [],
            provenance=provenance or {},
            error=None
        )

    @classmethod
    def error_result(
        cls,
        tool_name: str,
        error_type: str,
        message: str,
        details: Optional[List[str]] = None,
        provenance: Optional[Dict[str, Any]] = None
    ) -> "ToolResult":
        """Construct an error ToolResult."""
        return cls(
            tool_name=tool_name,
            status="error",
            result={},
            artifacts=[],
            provenance=provenance or {},
            error=ToolError(error_type=error_type, message=message, details=details or [])
        )


class BaseTool(ABC):
    """Abstract Base Class for all deterministic scientific tools."""

    name: str
    description: str
    arguments_schema: Optional[Type[BaseModel]] = None  # Pydantic model for argument validation

    def validate_arguments(self, arguments: Dict[str, Any]) -> Tuple[bool, Optional[BaseModel], Optional[str]]:
        """Validate input arguments dictionary against arguments_schema if defined."""
        if not self.arguments_schema:
            return True, None, None

        try:
            validated = self.arguments_schema(**arguments)
            return True, validated, None
        except ValidationError as ve:
            err_msg = f"Argument validation failed for tool '{self.name}': {ve}"
            return False, None, str(ve)
        except Exception as e:
            return False, None, str(e)

    def run(self, arguments: Dict[str, Any]) -> ToolResult:
        """Safe execution wrapper: validates arguments first, then invokes _execute()."""
        is_valid, validated_args, err_detail = self.validate_arguments(arguments)
        if not is_valid:
            return ToolResult.error_result(
                tool_name=self.name,
                error_type="ArgumentValidationError",
                message=f"Invalid arguments supplied to tool '{self.name}'.",
                details=[err_detail] if err_detail else []
            )

        try:
            return self._execute(arguments=arguments, validated_args=validated_args)
        except Exception as e:
            return ToolResult.error_result(
                tool_name=self.name,
                error_type=type(e).__name__,
                message=f"Tool execution failed: {str(e)}"
            )

    @abstractmethod
    def _execute(self, arguments: Dict[str, Any], validated_args: Optional[BaseModel] = None) -> ToolResult:
        """Internal execution logic to be overridden by subclasses."""
        pass
